### ISSUE TITLE
Should we have a naming standard for feature branches, and should it be "feat/..." or "feature/..."?

### ISSUE THREAD

**Issue by steinmy** [3lvia/kunde-elvia-web#156]
Having different names makes it harder to find the branch you're looking for when tools organize them into folders:
![image](https://user-images.githubusercontent.com/20183313/95213407-12dd4000-07ef-11eb-95a4-fc70ed075fae.png)

**Comment by steinmy** [comment]
This was discussed a bit on Slack, but no conclusion was reached

**Comment by eTallang** [comment]
I'll vote for `feature/` since it appears to me that most use that term :slightly_smiling_face:

**Comment by FredricW** [comment]
I agree with Tallang on this :)

**Comment by steinmy** [comment]
Konklusjon: Vi følger typene til conventional commits, altså bruker vi `feat/` i starten av branchnavn for feature branches, og tilsvarende for branches som passer inn i de andre kategoriene til conventional commits.
